### ISSUE TITLE
How to present different result regarding to different web browser

### ISSUE THREAD

**Issue by Jeffxz** [w3c/epub-tests#106]
The use case is for such as mathml support some reading system has dependency on web browser to support so we will need a way to present "mathml can be supported on Safari" and "mathml can not be supported on chrome" for some web based reading system. I wonder if there is a way to present this difference.

**Comment by dlazin** [comment]
I think this is addressed by @iherman 's comment https://github.com/w3c/epub-tests/pull/102#discussion_r782732607, and thus by your https://github.com/w3c/epub-tests/pull/105 (which implements his suggestion correctly).

Is that sufficient (so that we can close this issue), or am I misunderstanding some subtlety?

**Comment by iherman** [comment]
> I think this is addressed by @iherman 's comment [#102 (comment)](https://github.com/w3c/epub-tests/pull/102#discussion_r782732607), and thus by your #105 (which implements his suggestion correctly).
> 
👍

**Comment by Jeffxz** [comment]
Thanks @dlazin. Yes lemme close this one.
Also, in today's CG meeting you mentioned there might be some candidate for test cases to implement. Can you pls point me where I could find it? I think can get some time to write some test. Creating test contents is also fun!

**Comment by iherman** [comment]
> Thanks @dlazin. Yes lemme close this one.
> Also, in today's CG meeting you mentioned there might be some candidate for test cases to implement. Can you pls point me where I could find it? I think can get some time to write some test. Creating test contents is also fun!

I do not think we have an explicit list (I may be wrong on that). However, a neat trick is as follows. If you go to the editors' drafts of a spec, say, the [RS spec](https://w3c.github.io/epub-specs/epub33/rs/), for a number of _MUST_ statement (say, in https://w3c.github.io/epub-specs/epub33/rs/#sec-pub-resources) you will see a small pull down menu denoted as 'tests'. Those refer to the number and the links to the tests that are already existing. You may of course choose some additional tests, but better look for sections, functionalities, etc, in the text that does _not_ have such tests but that should (at the end of the day, the goal is to have at least one test for each _MUST_ statement).

B.t.w., https://w3c.github.io/epub-tests/contributing is your friend on how to write a test...

Note also that I will merge, hopefully later today, https://github.com/w3c/epub-tests/pull/100, which includes a number of tests on the scripting environment. Once there, I would be very interested to see how your implementation fare with those!

**Comment by Jeffxz** [comment]
awesome. Thanks @iherman. lemme read through. Someitem I might be able to help write test that wysebee can use as well.
