### ISSUE TITLE
Test external links

### ISSUE THREAD

**Issue by Jeffxz** [w3c/epub-tests#120]
I will test the following normative statement:

https://w3c.github.io/epub-specs/epub33/rs/#sec-epub-rs-external-links

Reading Systems SHOULD open links that resolve outside the [EPUB Publication](https://www.w3.org/TR/epub-33/#dfn-epub-publication) in a new browser instance to ensure that the security and privacy controls of the browser are available to users.

**Comment by Jeffxz** [comment]
Should I close this one since test is added?

**Comment by iherman** [comment]
@Jeffxz closing this indeed
