### ISSUE TITLE
basic MO audio rendering test tests more than basic MO audio rendering

### ISSUE THREAD

**Issue by marisademeglio** [w3c/epub-tests#151]
In addition to if an audio clip is played from clip start to clip end, it also tests if the text is highlighted and if the reading system has a button to start playback (which is technically not a requirement, if the RS just started playback automatically we would still say it supports MO).

The relevant commit is https://github.com/w3c/epub-tests/commit/631baf09fe6eb2003703e29092e8063e9cbf2f06

**Comment by dlazin** [comment]
Yeah, I just copied from Ivan's earlier MO tests, like https://github.com/w3c/epub-tests/blob/main/tests/mol-audio-exceeding-clipend/EPUB/content_001.xhtml. I'm very much open to changing it (and making all the MO tests consistent), just need to decide on the standard language. @iherman thoughts?

**Comment by iherman** [comment]
I agree with @marisademeglio that it uses the CSS part. The reason it was added/kept in the tests was, I believe, to make the test's evaluation easier to testers, and I think it is important, too. Note that the xhtml text says, in the description of the testing result:

> If the reading system highlights the active text, then the highlight stops at the second section

What I meant here is to help the evaluator but if the system does not highlights the active text (ie, the system does not highlights texts) the overall test could also pass.

Dan, I am sure you can reformulate the intention to make this distinction better...
