### ISSUE TITLE
Test OCF other files in meta-inf folder

### ISSUE THREAD

**Issue by Jeffxz** [w3c/epub-tests#155]
I will add test for following statement.

> Reading systems MUST NOT fail when encountering configuration files in the META-INF directory not listed in Reserved files [epub-33].

https://w3c.github.io/epub-specs/epub33/rs/#sec-container-metainf-inc

**Comment by Jeffxz** [comment]
PR for test case can be found here https://github.com/w3c/epub-tests/pull/156
PR for adding test reference can be found here https://github.com/w3c/epub-specs/pull/2315/commits/d743ba574478c54de5b242bdf9ad06d8e0f87119

**Comment by iherman** [comment]
closing this issue, since it has all been done. Thanks @Jeffxz
