### ISSUE TITLE
Is this a valid test for prefix mapping?

### ISSUE THREAD

**Issue by iherman** [w3c/epub-tests#158]
There is a statement [in the RS document](https://www.w3.org/TR/epub-rs-33/#sec-pkg-doc-manifest):

> If any of the properties attribute's values do not include a prefix [epub-33], reading systems MUST use the prefix URL "http://idpf.org/epub/vocab/package/item/#" to expand the values.

@dlazin wonders whether this (and similar) statements can be tested in the first place.

I tried to come up with a testing strategy and, before I put it into the test suite, I wanted to check whether this is indeed a good test.

**Version 1.** I create a simple test with a single content file, but with a package document of the form:

```xml
<package xmlns="http://www.idpf.org/2007/opf" xmlns:epub="http://www.idpf.org/2007/ops" 
  version="3.0" xml:lang="en" unique-identifier="pub-id" 
  prefix="myown: http://idpf.org/epub/vocab/package/item/#">
  <metadata xmlns:dc="http://purl.org/dc/elements/1.1/">
    ...
  </metadata>
  <manifest>
    ...
    <item id="nav" properties="myown:nav" href="nav.xhtml" media-type="application/xhtml+xml" />
  </manifest>
  ```

This is _not_ a valid EPUB insofar as there is a statement in the core whereby one _MUST NOT_ define a prefix for a default vocabulary. Epubcheck flags this, and that is fine. 

**Version 2.** I modify the EPUB to use `prefix="myown: http://example.org/#"`. 

My expectation would be that a RS should open the first version without further ado, ie, the TOC should be identical to the 'classic' case when no prefix is used. On the other hand, the second case should either provide no TOC or some sort of a default, RS-dependent TOC (eg, a list of file names).

Is this correct? There is an uncertainty whereby the first version is, as I said, not 100% correct, so a RS might refuse it, too...

Cc @wareid @dauwhe @rdeltour @danielweck

**Comment by iherman** [comment]
> Not if I understand you correctly. In that case, you'd no longer have a nav declaration, only some unknown property: http://example.org/#nav
> 
> Or does your first version declare a nav without the prefix in another manifest entry? Or are you adding that to your second to make sure the unknown property is ignored?

No, in the first version the prefix is defined for the default, official URL, ie, `http://idpf.org/epub/vocab/package/item/#`!

**Comment by iherman** [comment]
> Right, but what does it mean to open the first version when you change the prefix in the second version? The best I can understand is you mean you'll do this:
> 
> ```
> <package ... prefix="myown: http://example.org/#[](http://example.org/#)">
> 
>     <item id="nav" properties="myown:nav" href="nav.xhtml" media-type="application/xhtml+xml" />
> ```
> 
> So you no longer have a nav property declaration unless you've included an unprefixed version in the elided markup.

I am sorry, I was not clear. I created _two_ EPUB instances: version 1 and version 2. The first EPUB is using the prefix with the official URL, the _second_ EPUB is using it with `example.org`. What I am saying is that a RS should display the _first_ EPUB just as if the prefix was not used at all because, after all, the prefix is "just" defining what the default URL mapping would do anyway. The prefix is unnecessary, but should not change the behaviour.

The _second_ EPUB _should_ go wrong of course.

**Comment by iherman** [comment]
*If* it is not required to resolve the prefix, then this should be made clear somehow. The current text suggests (at least for me, but I am of course biased by my RDFa past) that the prefix mechanism is in place in the package document, and the _MUST_ statements in the RS specs certainly suggest the same...

**Comment by mattgarrish** [comment]
I'll have a look this morning, but I was expecting it was one of those situations where if you resolve the CURIEs, then here are the requirements for doing so.

We never wanted to burden reading systems with that processing, only provide a pathway for moving between our quasi-RDFa and real RDFa. It was also to allow translation between the package metadata and a "real" format in the future with minimal information loss. In that way it's somewhat useful, even though on most days it feels like a lot of bloat to foist on authors and reading systems for processing that probably not used much in practice.

**Comment by mattgarrish** [comment]
I'll open an issue in the main tracker, too, as we should probably find out how reading system devs have interpreted this.

**Comment by iherman** [comment]
B.t.w., I tested these on a RS (Thorium) and it failed on version 1. It clearly did not recognize the nav file with the prefix URL.

**Comment by iherman** [comment]
This has become moot, because the prefix mapping is optional...
