### ISSUE TITLE
"publisher" metadata is present in the OPDS feed, not in `package.opf`

### ISSUE THREAD

**Issue by danielweck** [w3c/epub-tests#161]
https://github.com/w3c/epub-tests/blob/fcd9a4fce472e200b759a1cd78eb028731d52066/src/lib/opds.ts#L81

vs.

https://github.com/w3c/epub-tests/blob/447aa8d1cf792bc66c05279726d54ee476f8bb4f/tests/cnt-css-fonts/EPUB/package.opf#L3-L15

Suggestion: add `<dc:publisher>W3C</dc:publisher>` to match the metadata of the OPDS feed.

ping @iherman https://github.com/w3c/epub-tests/pull/157

**Comment by danielweck** [comment]
Note the lack of "publisher" info in Thorium's local bookshelf (column on the right hand side):

![Screenshot 2022-06-08 at 07 56 19](https://user-images.githubusercontent.com/625201/172555478-1e1856c6-1e0f-4654-ad46-ccd58bde1aa4.jpg)

**Comment by iherman** [comment]
@danielweck just to understand: you mean I should add an xml fragment as a value of the key, ie,

```json
{
  ...
  "publisher": "<dc:publisher>W3C</dc:publisher>"
}
```

or should it be

```json
{
...
    "dc:publisher": "W3C"
}
```

My JSON-LD/RDF instinct tell me I should do the latter, but it is not clear from the spec...

**Comment by danielweck** [comment]
The metadata is missing in `package.opf` XML files. The OPDS feed is fine.

**Comment by iherman** [comment]
Oops, sorry, I misunderstood you!

Then this is a bug in the tests. Is the list in https://github.com/w3c/epub-tests/issues/161#issuecomment-1149553520 the complete list of tests without publishers? We will have to take care of that in the tests...

cc @dlazin

**Comment by danielweck** [comment]
The Thorium screenshot only shows a partial list of tests. I believe none of the tests include `<dc:publisher>W3C</dc:publisher>` in `package.opf` metadata.

**Comment by iherman** [comment]
Actually... it was easy. I have a script that can be used to add new metadata items for all tests in one step... 😀

See #162
