### ISSUE TITLE
The "acid" test is not specific enough (not "unit" testing) + fails with typical stylesheet overrides from reading system "user agent" and/or user formatting preferences

### ISSUE THREAD

**Issue by danielweck** [w3c/epub-tests#164]
Screenshot from Apple iBooks / MacOS Books.app (same broken rendition with Thorium):

<img width="218" alt="Screenshot 2022-06-15 at 14 34 52" src="https://user-images.githubusercontent.com/625201/173869002-a3cc6268-0e82-433e-9a0e-71cf2c96f626.png">

* Direct HTML link (successful rendering in a "vanilla" web browser, with default user agent stylesheet and no major user styling customisations): https://raw.githack.com/w3c/epub-tests/main/tests/cnt-css-support/EPUB/content_001.xhtml#top
* EPUB download link: https://github.com/w3c/epub-tests/blob/main/tests/cnt-css-support.epub

The rationale for including the Acid test in the EPUB test suite was mentioned in this PR https://github.com/w3c/epub-tests/pull/7

> I also made a version of the Acid2 test, as that seemed one way to test the requirement about reading systems with a viewport: "If it has a Viewport, it MUST support visual rendering of XHTML Content Documents as defined in § 4.3.1 CSS Conformance."

This Acid test was indeed a useful exercise that offered a vivid visual demonstration of the shortcomings of some competing CSS implementations in web browsers and other rendering engines. However I think the value of Acid test in the context of the EPUB test suite is arguably debatable because it is not clear what feature is tested exactly. Furthermore, reading systems typically apply a default "user agent" stylesheet (+ additional overrides based on user preferences) that cause different rendering than vanilla web browsers. For example, pagination using CSS columns usually involves overriding margins, etc.

My recommendation would be to eliminate the Acid test from this test suite.

**Comment by danielweck** [comment]
CC @llemeurfr @gautierchomel

**Comment by iherman** [comment]
cc @dauwhe @dlazin

**Comment by dauwhe** [comment]
> My recommendation would be to eliminate the Acid test from this test suite.

I'm fine with that. As I mentioned, it was one way of showing that an RS supports "a lot" of CSS, but it is a strange test (and had to be edited to be XHTML, etc.)

**Comment by iherman** [comment]
I have created a PR to do so (#167). 

However, we have now a _MUST_ statement on being conform to CSS that has now corresponding test (actually, we have the statement twice: one in the introductory statement in the paragraph and then one in the core text of [§6.3](https://w3c.github.io/epub-specs/epub33/rs/#sec-css). This contradicts to the requirement for having a test for each _MUST_ statement. I am not sure whether this is a problem and what we should put there instead.

(Almost all our tests use CSS in some way. One could argue that CSS support is amply shown through the test suite... but maybe removing the first bullet item, which is a repetition of what is said in the yellow banner, makes things a big cleaner. This is reminiscent on the discussion in https://github.com/w3c/epub-specs/pull/2330)

cc @dlazin @mattgarrish

**Comment by dlazin** [comment]
I agree with removing this; I have similar thoughts, but haven't found time to create a replacement test. Note that I think it's fine to use a basic test for two different normative statements, if it reasonably tests the same things; not as good as having unique tests, but IMO fine. I don't think there's a meaningful difference between "you must support rendering CSS" and "you must support CSS as defined in the CSS spec"; one basic test seems sufficient to me.

**Comment by iherman** [comment]
> one basic test seems sufficient to me.

me too. But, with the removal of this test, there is no test for the statements in [§6.3](https://w3c.github.io/epub-specs/epub33/rs/#sec-css). Even if we decide to remove the bullet item:

> MUST support the official definition of CSS as described in the [[csssnapshot](https://w3c.github.io/epub-specs/epub33/rs/#bib-csssnapshot)].

(which I would agree with), we may still to either have, or assign another test, for the statement in the intro part of the section, i.e., 

> If a reading system has a [viewport](https://www.w3.org/TR/epub-33/#dfn-viewport), it MUST support the [visual rendering of XHTML content documents via CSS](https://www.w3.org/TR/epub-33/#sec-css) [[epub-33](https://w3c.github.io/epub-specs/epub33/rs/#bib-epub-33)].

So far, the acid test was used for both.
