### ISSUE TITLE
Test OCF zip file split across multiple storage media

### ISSUE THREAD

**Issue by Jeffxz** [w3c/epub-tests#176]
I will test

MUST treat any [OCF ZIP container](https://www.w3.org/TR/epub-33/#dfn-ocf-zip-container) that specifies the [[zip](https://w3c.github.io/epub-specs/epub33/rs/#bib-zip)] file is split across multiple storage media as in error.

from https://w3c.github.io/epub-specs/epub33/rs/#confreq-zip-mult

**Comment by iherman** [comment]
Test done and merged earlier today.
