### ISSUE TITLE
License for the tests

### ISSUE THREAD

**Issue by xfq** [w3c/epub-tests#177]
https://github.com/w3c/epub-tests/blob/main/CONTRIBUTING.md

> Contributions to this repository are intended to become part of Recommendation-track documents governed by the [W3C Patent Policy](https://www.w3.org/Consortium/Patent-Policy-20040205/) and [Software and Document License](https://www.w3.org/Consortium/Legal/copyright-software). To make substantive contributions to specifications, you must either participate in the relevant W3C Working Group or make a non-member patent licensing commitment.

From what I understand, the tests themselves are not part of Recommendation-track documents, and the licenses used for tests elsewhere in W3C (see [1](https://github.com/web-platform-tests/wpt/blob/master/LICENSE.md) and [2](https://github.com/w3c/licenses/blob/main/TEST-LICENSE.md)) don't seem to be using the [Software and Document License](https://www.w3.org/Consortium/Legal/copyright-software).

**Comment by iherman** [comment]
Oops. Thanks @xfq for spotting that. What happened is that I used the [automatic procedure](https://labs.w3.org/repo-manager/repo/new) to set up a new W3C repository (which included a "contributing" file) and I never checked this. My mistake.

Indeed, the tests are not recommendation track documents. Note, however, that the tests themselves (which are individual epub instances) are published under the Software and Document Licenses (see, e.g., https://github.com/w3c/epub-tests/blob/main/tests/cnt-svg-css/EPUB/package.opf). This is necessary for the particularities of the EPUB testing procedure.

I am still on vacations this week, but I will take care of it next week (unless sometimes beats me into it).

P.S. @plehegar it may make sense to modify the repo manager to offer different types of "contributing" files...

**Comment by xfq** [comment]
Thanks, Ivan. BTW, in [package.json](https://github.com/w3c/epub-tests/blob/f965f891c8f884cc97605ce9e1566bc667ebb917/package.json#L20) it's the ISC License.

**Comment by iherman** [comment]
> Thanks, Ivan. BTW, in [package.json](https://github.com/w3c/epub-tests/blob/f965f891c8f884cc97605ce9e1566bc667ebb917/package.json#L20) it's the ISC License.

That is all right. The package.json is for the script that runs as a github action and that produces the readable reports.

**Comment by plehegar** [comment]
Catching up here.

The license for WPT is not a W3C license. It is using its own on purpose (long story short: WPT is not under W3C by design).

As linked above, https://github.com/w3c/licenses/ contains the diverse licenses used by W3C on Github but there is only [one license](https://github.com/w3c/licenses/blob/main/TEST-LICENSE.md) recommended for test suites nowadays.

As such, the repo manager shouldn't give a choice but rather should ask the usage of the future repo. At the moment, we only support creating REC-track repositories through that tool.
