### ISSUE TITLE
Test OCF containers that use compression techniques other than Deflate

### ISSUE THREAD

**Issue by Jeffxz** [w3c/epub-tests#185]
I will test

> MUST treat any OCF ZIP container that uses compression techniques other than Deflate [[rfc1951](https://w3c.github.io/epub-specs/epub33/rs/#bib-rfc1951)] as in error.

from https://w3c.github.io/epub-specs/epub33/rs/#confreq-zip-comp

**Comment by iherman** [comment]
#188 merged, closing
