### ISSUE TITLE
Differentiate non-applicable tests from untested tests in the report

### ISSUE THREAD

**Issue by gregoriopellegrino** [w3c/epub-tests#237]
I think we had mentioned this at TPAC, but I don't remember if we had arrived at a solution.

Right now in the report we can enter three values: `true`, `false` and `null`.

The thing is that `null`, in my case means either not applicable, or not yet tested (or to be rechecked because there are problems with the reader).

Can it make sense to split these two different pieces of information?

**Comment by iherman** [comment]
Something _could_ be done, of course (adding an explicit `n/a` value, with `null` becoming the "not tested yet"; whether it is worth the trouble. The trouble being (1) a bit of coding (but that is only my trouble, and I can handle it) and (2) what to do with the test results that are already on site.

The simplest maybe if those who are involved in testing vote with a 👍 or 👎 for adding this or not, respectively.

@bduga @wareid @Jeffxz @davemanhall @llemeurfr

**Comment by wareid** [comment]
I think "n/a" would be a good addition, especially it might help contextualize failures or untested (i.e. the MP4 video test on eink devices which counts as a fail when it really should be n/a). Good for viewers of the results as well.

**Comment by bduga** [comment]
+1 to n/a.

**Comment by davemanhall** [comment]
Ditto.  +1 n/a

**Comment by iherman** [comment]
It seems clear that this would be useful. I will try to change the code accordingly soon. PR to come... (at some point)
