### ISSUE TITLE
Test categorization

### ISSUE THREAD

**Issue by iherman** [w3c/epub-tests#260]
I have just added a PR (#259) to, hopefully, improve the test presentation pages. I have also realized that we may want to review the 'test categorization' we use for the tests, ie, the subsections that appear on the TOC (publication resources, core media types, etc). These are my problems:

- There is a section called "Layout rendering" which appeared, afair, when the section on fixed layout has bee reorganized. On the other hand, that contains only two must tests, which does not seem clear on whether it is worth having the section. Should it be merged with "Fixed Layout" with a possibly different category name?
- I realized that we do not even have a separate section for fallbacks, although this is the most touchy issue in terms of test results. Shouldn't we create one, and move the relevant tests there?

Unfortunately, it is not an easy operation, so we have to discuss it first. Indeed, to implement any change, we have to change the metadata in all relevant tests, which is a somewhat tedious thing to do, so we should have an agreement on what we really want to change, if anything.

CC @dlazin @wareid @mattgarrish @dauwhe @shiestyle

**Comment by wareid** [comment]
Layout rendering could live with FXL, it's weirdly applicable to both reflow and fxl, which was it's challenge. 

Having the fallback tests grouped would be helpful I think.
