### ISSUE TITLE
mol-navigation references wrong audio file

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-tests#275]
ch2.smil has this `par` for playing back the first sentence in chapter 2:

```
    <par>
      <text src="../ch2.xhtml#mo-2"/>
      <audio src="../audio/ch1.mp3" clipBegin="00:00:01.365" clipEnd="00:00:07.048"/>
    </par>
```

Notice that it references ch1.mp3, so you get the wrong playback audio even though the test is working correctly.

**Comment by iherman** [comment]
I am not sure which tests you are talking about...
