### ISSUE TITLE
Do we want to list test authors in an acknowledgement section?

### ISSUE THREAD

**Issue by iherman** [w3c/epub-tests#28]
The title tells it all... I can easily extend the automatic generation scripts by collecting the creator metadata from the package document alongside the attributes that are to be extracted anyway. The script would then create an acknowledgement section into the test description document.

Should we do this?

@dlazin @dauwhe @wareid

**Comment by dlazin** [comment]
I think it's a nice idea — a small incentive for people to write tests. Spec editors are listed at the top of the spec, so listing test authors makes sense.

**Comment by iherman** [comment]
Would you want to add them as editors of the test program in the header? That would be a bit more complex (not all test authors are necessarily members of the WG and any editor is supposed to be). I thought of having a separate section either at the beginning or the end of the test description file listing the names as contributors.

**Comment by dauwhe** [comment]
+1 to this idea
