### ISSUE TITLE
Missing test pkg-spine-nonlinear "usable"

### ISSUE THREAD

**Issue by gautierchomel** [w3c/epub-tests#283]
The [pkg-spine-nonlinear-activation](https://github.com/w3c/epub-tests/tree/main/tests/pkg-spine-nonlinear-activation) test shows that nonlinear resources are reachable. It does not presumes if this reachable resource is usable.

Most often what happens is that you can reach the nonlinear resource but once there you can't navigate thru this resource (because it is nonlinear).

A similar test with a long nonlinear resource will show that this spec is not implemented in a usable way.

**Comment by iherman** [comment]
@dauwhe, this is your baby... :-)

@gautierchomel, do you think you could put in a PR with an improved test?

**Comment by gautierchomel** [comment]
Proposed test addition per #288.

**Comment by iherman** [comment]
Closed by virtue of https://github.com/w3c/epub-tests/pull/288#issuecomment-1385386457
