### ISSUE TITLE
Test RS processing of data URLs

### ISSUE THREAD

**Issue by m22chan** [w3c/epub-tests#53]
This test the normative statement found at:

https://www.w3.org/TR/epub-rs-33/#confreq-rs-data-urls
Reading Systems MUST prevent data URLs [RFC2397] from opening in top-level browsing contexts.

**Comment by dlazin** [comment]
There are now two normative statements here, and I think they both need tests:

> Reading Systems MUST prevent data URLs [RFC2397] from opening in top-level browsing contexts [HTML], except when initiated through a Reading System affordance such as a context menu. If a Reading System does not use a top-level browsing context for Top-level Content Documents, for example if the Top-level Content Document is an SVG, it MUST also prevent data URLs from opening as though they are Top-level Content Documents.

https://w3c.github.io/epub-specs/epub33/rs/#sec-epub-rs-conf-data-urls

**Comment by m22chan** [comment]
Ah, I see. So we need something specifically for:

> If a Reading System does not use a top-level browsing context for Top-level Content Documents, for example if the Top-level Content Document is an SVG, it MUST also prevent data URLs from opening as though they are Top-level Content Documents.

I can make a test book with 2 content documents in the spine.
First content document explains test and contains data: URL version of an SVG.
Second content document contains just text.
Test passes if the RS displays the test book as _two_ top-level content documents - i.e. page 1 and page 2, without inserting a page in between for the SVG.

**Comment by iherman** [comment]
Should have been closed a long time ago by virtue of having merged #54...
