### ISSUE TITLE
Test RS processing of linked metadata record in package document

### ISSUE THREAD

**Issue by m22chan** [w3c/epub-tests#56]
I'll write a test for this normative statement:

https://w3c.github.io/epub-specs/epub33/rs/#sec-linked-records
In the case of a linked metadata record [EPUB-33], Reading Systems MUST NOT skip processing the metadata expressed in the Package Document and only use the information expressed in the record.

The test also relates to:

https://w3c.github.io/epub-specs/epub33/core/#sec-linked-records
EPUB Creators MAY provide one or more linked metadata records to enhance the information available to Reading Systems, but Reading Systems may ignore these records.

**Comment by iherman** [comment]
These have been done, issue was not closed...
