### ISSUE TITLE
testing processing of XML Names

### ISSUE THREAD

**Issue by dauwhe** [w3c/epub-tests#6]
An EPUB Reading System "[MUST be a conformant processor](https://w3c.github.io/epub-specs/epub33/rs/#confreq-rs-xml-ns) as defined in [XML-NAMES](https://www.w3.org/TR/xml-names/)."

Looking at XML Names, we find

> To conform to this specification, a processor MUST report violations of namespace well-formedness, with the exception that it is not REQUIRED to check that namespace names are URI references [RFC3986].

> It follows that in a namespace-well-formed document:
> * All element and attribute names contain either zero or one colon;
> * No entity names, processing instruction targets, or notation names contain any colons.

I suppose this means we write some tests with element names like `p::p`. But this all means that an EPUB Reading System is obligated to report a very technical error to the end user. 

***

Is this our goal? My perhaps-naive view is that [1] we don't want reading systems to mess up the namespaces they already have to deal with and [2] we want to be able to use namespaces to change the rendering of the document via CSS.

**Comment by dauwhe** [comment]
So... made a tiny test with a `p::p` tag in the content doc. Apple Books, Thorium, and ADE 4.5 showed the parse error:

<img width="489" alt="Screen Shot 2021-01-05 at 12 06 00 PM" src="https://user-images.githubusercontent.com/5687700/103675842-670ed200-4f4e-11eb-8eca-86584b2e8ef9.png">

Calibre did not complain in any way. So I guess it's a useful test if it highlights differences amongst reading systems...

**Comment by dlazin** [comment]
This is (at least somewhat) tested:
https://w3c.github.io/epub-specs/epub33/rs/#sec-epub-rs-conf-xml

Should we close this issue? I vote yes, and so will do it, but reopen if more is needed.
