### ISSUE TITLE
Clarify what's invalid in confreq-rs-xml-nval_invalid

### ISSUE THREAD

**Issue by dlazin** [w3c/epub-tests#66]
I added metadata to https://github.com/w3c/epub-tests/blob/main/tests/confreq-rs-xml-nval_invalid/OPS/package.opf (and renamed it, formerly `xml-non-validating-parser-002`), but it wasn't clear to me *what*'s invalid in that test. Please clarify the test description and name, and possibly rename the test directory (and update test references in the spec).

By comparison, https://github.com/w3c/epub-tests/blob/main/tests/confreq-rs-xml-nval_unclosed/OPS/package.opf (same normative statement) is clear (but it could also be called "invalid," which is why "invalid" isn't good enough).

**Comment by dauwhe** [comment]
That's a really good question. Working on it :)

**Comment by dauwhe** [comment]
Ah, I think it got merged before it was finished. The idea was to have at least some sort of test of the requirement that EPUB reading systems be "conformant, non-validating parsers" for XML. So the test comments out the nav element in the spine, to make sure the reading system understands XML comments. Not the most exciting test in the world.
