### ISSUE TITLE
Should we add a 'rights' entry to the metadata?

### ISSUE THREAD

**Issue by iherman** [w3c/epub-tests#68]
This issue came up during the [2nd vF2F day](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-10-29-epub): we may want to add a metadata item into the `package.opf` file, namely:

```xml
<dc:rights>https://www.w3.org/Consortium/Legal/2015/copyright-software-and-document</dc:rights>
```

The reason is that some reading systems will have to put a copy of the tests into another public space for testing, and the questions on rights may arise.

(Caveat: we would have to add this line to all opf files. Wonder whether this could be automatized; I am willing to look into this in case we otherwise agree.)

**Comment by iherman** [comment]
@wseltzer your reaction on this would be important!

**Comment by iherman** [comment]
If we want to be complete, we can also add a 'rightsHolder' term, too, pointing at W3C.

**Comment by iherman** [comment]
> If we want to be complete, we can also add a 'rightsHolder' term, too, pointing at W3C.

While this would be correct in terms of DC data, epubcheck complains; it is not an allowed metadata item.

I have a code on my machine which seems to be ready to go to regenerate all the tests with the rights metadata added. Should I?

@dauwhe @wareid @dlazin

**Comment by wseltzer** [comment]
@iherman can you share a pointer to a bit more description? What is it we'd be asserting with that statement? 
It seems uncontroversial if it's just linking the terms of the license.

**Comment by mattgarrish** [comment]
> While this would be correct in terms of DC data, epubcheck complains; it is not an allowed metadata item.

It's not an element in the DC set, if that's what you mean, but there's no reason you can't specify these as rel values on a `link`:

```
<link rel="dcterms:rights" href="https://www.w3.org/Consortium/Legal/2015/copyright-software-and-document"/>
<link rel="dcterms:rightsHolder" href="..."/>
```

`meta` tags always strike me as ugly for URLs, but you could do it that way, too:

```
<dc:rights>https://www.w3.org/Consortium/Legal/2015/copyright-software-and-document</dc:rights>
<meta property="dcterms:rightsHolder">...</meta>
```

**Comment by dlazin** [comment]
I am cool with putting such metadata in every package. But are you talking about writing it programmatically as some sort of post-processing, or just a bulk GitHub edit? Bulk edit sounds good to me. I am uncomfortable with writing things into the EPUBs that are not visible in the uncompiled source, though.

**Comment by iherman** [comment]
> @iherman can you share a pointer to a bit more description? What is it we'd be asserting with that statement?
> It seems uncontroversial if it's just linking the terms of the license.

Apologies @wseltzer, I should have add some explanations indeed.

The WG is developing a bunch of EPUB 3 Tests[1]; each test is a separate epub file. As discussed on our last vF2F[2] and the issue that surfaced is that, to perform the testing, reading system developers may have to make a copy of all tests and incorporate them in their usual publication pipeline. In some cases this means that these tests would appear to the outside world as bona fide digital books to be downloaded. By itself it is not a problem, but the question did arise during the call whether this is, legally, all right[2].

While we agreed that should be the case, it sounded better to make it very clear in the ebooks themselves. Per EPUB, the metadata that are valid for the publication as a whole are part of what is called the package document. The proposal is to add the proposed DC statements to all the tests in [1].

I hope this helps.


[1] https://w3c.github.io/epub-tests/  
[2] https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-10-29-epub#section3

**Comment by iherman** [comment]
> It's not an element in the DC set, if that's what you mean

indeed, I got that wrong. But I can indeed use the meta element; for symmetry, I will use it for both statements.

Thx

**Comment by iherman** [comment]
> I am cool with putting such metadata in every package. But are you talking about writing it programmatically as some sort of post-processing, or just a bulk GitHub edit? Bulk edit sounds good to me. I am uncomfortable with writing things into the EPUBs that are not visible in the uncompiled source, though.

A bulk edit. I have now a script running on my machine which modifies the metadata section of each test 'directory' and, through a separate step, all the directories are used to generate new epub files. Ie, if we agree with us doing this, there will be one super-mega PR with all the tests modified...

**Comment by dlazin** [comment]
Sure, go for it! I don't have any open edits at the moment, so no merge concerns.

**Comment by iherman** [comment]
It will still take 1-2 days to finalize things on my end, though. But, for the time being, it is code development and I do local tests (not on the real tests) yet. So if there is a merge done on the repo, I can handle it.
