### ISSUE TITLE
Additional metadata for MUST and SHOULD?

### ISSUE THREAD

**Issue by iherman** [w3c/epub-tests#74]
At the moment, all our tests are related to MUST statements but, eventually, we may also have tests for SHOULD-s. The distinction is significant for reporting: for the CR->PR transition, we will have to report the required number of implementations, whereas no such requirement exists for SHOULD-s. This difference must be clearly noted on the test report and this leads to the necessity to provide this information in the package metadata.

I did not find any obvious way to represent this information in the `dcterms` vocabulary. With a bit of an abuse of the existing vocabularies, I have come up with two different approaches.

One is to look at the tests as a collection in terms of the EPUB metadata vocabulary and add the following:

```xml
    <meta property="belongs-to-collection">must</meta>
```

The value for the `belongs-to-collection` term is `must` or `should`.

If this is considered to be an abuse, we could define our own "vocabulary":

```xml
<package … prefix="testType: https://www.w3.org/ns/test_types/">
...
    <meta property="testType:statement">must</meta>
...
```

again with the value of the terms defined as `must` or `should`.

In both cases the missing metadata value should be taken as a `must` by default (this means we do not require reworking all the current tests...

Any better approach?

Cc: @dlazin @mattgarrish @wareid @dauwhe 

---

As for the UI, my idea is to group the SHOULD tests at the end of the various tables, label all the rows with "M" or "S" (also, possibly display them with a slightly different background color). The point is that it should be clear to, mentally, separate the two category of tests when reviewing the results.

**Comment by dlazin** [comment]
I'm still thinking about this, but we do have at least *some* SHOULD tests already. Here's one:
https://w3c.github.io/epub-specs/epub33/rs/#sec-pkg-doc-pub-identifiers

**Comment by iherman** [comment]
> I'm still thinking about this, but we do have at least _some_ SHOULD tests already. Here's one:
> https://w3c.github.io/epub-specs/epub33/rs/#sec-pkg-doc-pub-identifiers

and, if we want to use this resource more widely than just the CR transition, then we should indeed have them...
