### ISSUE TITLE
Test publication resource internationalization

### ISSUE THREAD

**Issue by dlazin** [w3c/epub-tests#77]
This whole section needs tests:
https://w3c.github.io/epub-specs/epub33/rs/#sec-epub-rs-i18n

There are some similar tests in https://w3c.github.io/epub-tests/#sec-internationalization-data, but more are needed to satisfy this section.

**Comment by dlazin** [comment]
(I am not currently claiming these tests myself — this is just a tracking bug. If I claim these I will assign the issue to myself; until then anyone can grab this.)

**Comment by iherman** [comment]
Tests have already been added, closing...
