### ISSUE TITLE
Testing Linked Metadata Records

### ISSUE THREAD

**Issue by dauwhe** [w3c/epub-tests#8]
> Reading System do not have to use or present linked resources, even if they recognize the relationship defined in the rel attribute.

Which reading systems use linked metadata records? 

What record formats do they support? ONIX? MARC? Schema.org in some serialization? 

>   In the case of a linked metadata record [EPUB-33], Reading Systems MUST NOT skip processing the metadata expressed in the Package Document and only use the information expressed in the record. Reading Systems MAY compile metadata from multiple linked records; they do not have to select only one record.
>     When it comes to resolving discrepancies and conflicts between metadata expressed in the Package Document and in linked metadata records, Reading Systems MUST use the document order of link elements in the Package Document to establish precedence (i.e., metadata in the first linked record encountered has the highest precedence and metadata in the Package Document the lowest, regardless of whether the link elements occur before, within or after the package metadata elements).

We could override the book title in a linked resource, and see if it works :)

> Reading Systems MUST ignore any instructions contained in linked resources related to the layout and rendering of the EPUB Publication.

What are we trying to prevent here? Would the package doc link to, um, another package document that contains conflicting FXL metadata?

**Comment by mattgarrish** [comment]
> Would the package doc link to, um, another package document that contains conflicting FXL metadata?

A different serialization of it, I believe, yes. Wasn't this to avoid any confusion about precedence when we expected to define a web-friendly json version?

The closest we have now is a pub manifest, which isn't specifically defined for rendering, but in theory something like a conflicting page progression direction shouldn't override the package document.

I wouldn't call it a realistic test scenario, but linked resources kind of stray into an area where we could write a lot of tests and still not cover anything useful. Developers may be the only ones who can ever attest whether the restrictions are followed.

**Comment by dlazin** [comment]
Matthew seems to be working on this in https://github.com/w3c/epub-tests/pull/57.

**Comment by m22chan** [comment]
Hi everyone, the test merged in #57 assumes the linked metadata is ONIX. Is is only intended to test:

> In the case of a linked metadata record [EPUB-33], Reading Systems MUST NOT skip processing the metadata expressed in the Package Document and only use the information expressed in the record.

The test book I submitted isn't reflective of any real scenario that I could see in the publishing industry - I'll admit, haha.

**Comment by iherman** [comment]
Closing' #57 takes care of this.
