### ISSUE TITLE
Tests on the rendition properties

### ISSUE THREAD

**Issue by iherman** [w3c/epub-tests#82]
I will create tests for the [Rendition flow properties](https://www.w3.org/TR/epub-rs-33/#flow) (see also [in the content document](https://www.w3.org/TR/epub-33/#flow)).

---

Note, for the record, that these tests are not really my own. I looked at the old [IDPF test suite for 3.0](https://github.com/IDPF/epub-testsuite) to see whether and how those tests can be repurposed by adapting them to 3.3 and the tests on rendition seem to be the simplest to convert manually (those were written by @mattgarrish). The other tests may be more difficult to repurpose, their granularity vs. the document features is different.

@mattgarrish @dauwhe, do you see any issues doing this?

**Comment by dlazin** [comment]
Is this different from what Wendy's working on in https://github.com/w3c/epub-tests/issues/38? Suggest checking with her. (That issue could use more context.)

**Comment by iherman** [comment]
Yes it is. It is not related to fixed layouts, it is on whether content is paginated or scrolling, essentially.
