### ISSUE TITLE
Test prefix URL expansion

### ISSUE THREAD

**Issue by dlazin** [w3c/epub-tests#83]
There are four normative statements of this flavor:

> If the property attribute's value does not include a prefix, Reading Systems MUST use the prefix URL "http://idpf.org/epub/vocab/package/meta/#" to expand the value.

https://w3c.github.io/epub-specs/epub33/rs/#meta

They need tests, but how do we test this? What does passing look like? What does failing look like?

**Comment by dauwhe** [comment]
I don't know what tests would look like. One problem is that most of the values in the default namespace have no observable effects. 

Taking an example from the core spec:

```xml
<dc:identifier id="isbn-id">urn:isbn:9780101010101</dc:identifier>
<meta refines="#isbn-id" property="identifier-type" scheme="onix:codelist5">15</meta>
```

Say the reading system puts the `identifier-type` in the correct default  namespace. How would I ever know? 
Say the reading system puts the `identifier-type` in the wrong namespace. How would I ever know? 

***

The best I can think of is something like `<item properties='nav'>`. If the nav document shows up where it should be, that might mean that the reading system applied the correct default namespace. 

I know this is no help :)

**Comment by dlazin** [comment]
Example 72 here might be a good test:
https://www.w3.org/TR/epub-33/#d-1-2-the-property-data-type

That is, put in `<item … properties="mathml"/>` and `<item ... properties="http://idpf.org/epub/vocab/package/item/#mathml"/>` and `<item />` (containing MathML, but undeclared) and see if the first two work but the third does not.

(If the third one still works without the property being declared, then I suppose we have proved nothing.)

**Comment by iherman** [comment]
https://github.com/w3c/epub-specs/issues/2317 and its PR counterpart https://github.com/w3c/epub-specs/pull/2335 seems to make this issue moot. See also https://www.w3.org/TR/epub-rs-33/#sec-vocab-assoc.
